# Generated by Django 5.0.2 on 2024-02-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ceated_at',
            new_name='created_at',
        ),
    ]
