# Generated by Django 5.0.2 on 2024-02-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bloglikes',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='categoryblog',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='ceated_at',
            new_name='created_at',
        ),
    ]
