# Generated by Django 5.0.2 on 2024-02-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_ceated_at_blog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categoires',
        ),
    ]
