# Generated by Django 5.0.2 on 2024-03-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_categoires'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categoires',
            field=models.ManyToManyField(related_name='blogs', through='blog.CategoryBlog', to='blog.categories'),
        ),
    ]
