# Generated by Django 5.0.2 on 2024-03-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_categoires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categoires',
            new_name='categories',
        ),
    ]
