# Generated by Django 5.0.2 on 2024-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_categoires_blog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
